services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - PHP_VERSION=8.4
    image: mythresa-ali/php-fpm:app
    volumes:
      - ./:/var/www/html:rw,cached
      - ./docker/php/conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php/conf/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-app.conf:ro
    env_file:
      - .env
    networks:
      backend:
        aliases:
          - php
    depends_on:
      - mysql

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backend

  mysql:
    image: mysql:8.4
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      backend:
        aliases:
          - mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-shop}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-passw0rd}
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8082:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    networks:
      - backend
    depends_on:
      - mysql

networks:
  backend:
    driver: bridge

volumes:
  dbdata:
    driver: local
